CREATE DATABASE THUE_XE
GO
--
CREATE TABLE CUSTOMER
(
STT CHAR (5) not null,
CNAME NVARCHAR(50) ,
ADDRESSS NVARCHAR(50),
CELLPHONE INT,
CMND CHAR(11),
PRIMARY KEY (STT)
)
GO
--
CREATE TABLE CAR
(
NUMBER CHAR(5) NOT NULL,
COLOR NCHAR(5),
CONDITION nchar(5),
LOAI CHAR(3),
FEE INT ,
HANG NCHAR(10),
PRIMARY KEY (NUMBER)

)
GO
--
CREATE TABLE EMPLOYEES
(
ID CHAR(5) NOT NULL,
CMND CHAR(11),
ENAME NVARCHAR (50),
CELLPHONE INT ,
PRIMARY KEY (ID)
)
GO
--
CREATE TABLE HOPDONG
(
CODE CHAR(10) NOT NULL ,
ENAME NVARCHAR(50),
CNAME NVARCHAR(50),
STT CHAR(5),
ID CHAR(5),
DATE_RECIEVE DATE,
DATE_PAY DATE,
PRICE INT ,
DAYRENT INT,
NUMBER CHAR(5),
FEE INT,
CONSTRAINT FK_CUSTOMER  FOREIGN KEY (STT)    REFERENCES CUSTOMER(STT),
CONSTRAINT FK_EMPLOYEES FOREIGN KEY (ID)     REFERENCES EMPLOYEES(ID),
CONSTRAINT FK_CAR       FOREIGN KEY (NUMBER)    REFERENCES CAR (NUMBER),
PRIMARY KEY (CODE)
)
GO
--

UPDATE CAR
SET FEE =
CASE 
WHEN LOAI ='4' THEN 400
WHEN LOAI ='7' THEN 700
WHEN LOAI ='12'THEN 1000
ELSE 1200
END
GO

--
UPDATE CAR
SET FEE =FEE*CASE
WHEN LOAI ='4' AND HANG ='TOYOTA' THEN 1.25
END
GO
--

--
UPDATE HOPDONG
SET DAYRENT=CASE
WHEN  (DATE_PAY=DATE_RECIEVE) THEN 1
ELSE COUNT(DATE_PAY - DATE_RECIEVE)
END
GO
--
UPDATE HOPDONG
SET PRICE=FEE*DAYRENT
--
--
UPDATE HOPDONG
SET DATTRUOC =CASE
WHEN DAYRENT<3 THEN PRICE
WHEN 3<DAYRENT AND DAYRENT<5 THEN PRICE*0.75
WHEN DAYRENT>5 THEN PRICE*0.5
END
